-- The credits roll, as data. Read by states/credits.lua.
--
-- Authored, unlike its neighbour data/credits_icons.lua, which is generated by `. icon-build` and
-- appended automatically -- the icon attribution is a licence obligation and must never depend on
-- somebody remembering to update this file.
--
-- A section is `{ heading = ..., lines = { ... } }`. A `heading` with no `lines` is a spacer title; a
-- line of `false` is a blank row, which is how a long section is broken up without inventing a second
-- heading for it.
--
-- Keep the roll honest. An empty seat is left named-and-empty ("Music -- unfilled") rather than
-- quietly dropped, because a credits screen that lists only what exists reads as though nothing is
-- missing, and quite a lot is still missing. See docs/roadmap.md.
return {
    title = "LoveTactics",

    sections = {
        {
            heading = "Design & Code",
            lines = { "Keno San Pablo" },
        },
        {
            heading = "Written by",
            lines = { "Keno San Pablo" },
        },
        {
            heading = "Built with",
            lines = {
                "LÖVE2D  --  love2d.org",
                "Lua 5.1",
            },
        },
        {
            heading = "Art",
            lines = {
                "Character and portrait art -- unfilled",
                "Environment and hub art -- unfilled",
            },
        },
        {
            heading = "Music & Sound",
            lines = { "Unfilled" },
        },
        -- data/credits_icons.lua is appended after this point by states/credits.lua, so the icon
        -- attribution always lands last and always lands whole.
        {
            heading = "Thanks",
            lines = {
                "The LÖVE community",
                false,
                "and you, for going all the way down.",
            },
        },
    },
}
