-- GENERATED by `& "E:\LOVE\lovec.exe" . icon-build`. Do not hand-edit; re-run instead.
--
-- The machine-readable twin of docs/credits-icons.md. That file is for the repository; this one is
-- for the PLAYER -- states/credits.lua reads it so the game-icons.net attribution reaches the
-- credits screen, which is a condition of the CC BY 3.0 licence and not a courtesy.
return {
    source = "game-icons.net",
    url = "https://game-icons.net",
    licence = "CC BY 3.0",
    licenceUrl = "https://creativecommons.org/licenses/by/3.0/",
    count = 593,
    -- Author -> icons used. Sorted by name when written, so the file diffs cleanly.
    authors = {
        { name = "carl-olsen", count = 2 },
        { name = "caro-asercion", count = 22 },
        { name = "cathelineau", count = 5 },
        { name = "darkzaitzev", count = 10 },
        { name = "delapouite", count = 231 },
        { name = "faithtoken", count = 1 },
        { name = "generalace135", count = 1 },
        { name = "lorc", count = 275 },
        { name = "lucasms", count = 7 },
        { name = "sbed", count = 34 },
        { name = "skoll", count = 5 },
    },
}
