-- Where every SHIPPED silhouette comes from -- the ship gate for getting game-icons.net out of the build.
--
--     & "E:\LOVE\lovec.exe" . art-source           # the exposure, by bucket and by artist
--     & "E:\LOVE\lovec.exe" . art-source slugs      # ... and every outstanding slug, most-used first
--     & "E:\LOVE\lovec.exe" . art-source credits    # rewrite docs/credits-icons.md from this truth
--     & "E:\LOVE\lovec.exe" . art-source ship       # exit 1 if ANY shipped slug is still vendored
--
-- The point is a number nobody has to trust. docs/credits-icons.md claims 632 icons from game-icons.net,
-- but that file is generated by `icon-build` -- the SOURCING stage the composer superseded -- so it counts
-- what the old pipeline rendered, not what the shipped one draws. Both the licence obligation and the
-- "shipped with game-icons" exposure had been budgeted off it. This asks the composers instead.
--
-- It resolves each asset through the composer's OWN resolver (Icon.baseFor / Char.slugFor), so the report
-- cannot drift from the renderer: a change to how a base is picked moves this count on the next run. Then
-- it asks tools/icon_source.lua which root answers each slug, which is the whole measurement -- a slug
-- served by art/bases/ is drawn art we own, a slug served by vendor/game-icons is exposure still to buy.
--
-- Slugs are counted DISTINCT, and that is the finding the count exists to deliver: 749 item icons do not
-- need 749 drawings, they need however many distinct silhouettes they reduce to. The `slugs` mode sorts by
-- how many assets ride on each one, so the commission can be ordered by what buys the most screen.

local Registry = require("models.registry")
local Source = require("tools.icon_source")
local Icon = require("tools.icon_compose")
local Char = require("tools.char_compose")

local M = {}

-- The per-item glyph map is also the provenance record for the buckets `icon-build` renders DIRECTLY
-- (traps/, materials/, props/) -- those never pass through a composer, so the map is the only place that
-- knows which game-icons file became which PNG. Optional, the way the composers treat it.
local IconMap = nil
do
    local ok, m = pcall(require, "tools.icons.map")
    if ok and type(m) == "table" then IconMap = m end
end

local DIRECT_BUCKETS = { traps = true, materials = true, props = true }
local ORDER = { "items", "chars", "traps", "materials", "props" }

-- Every asset the shipped pipeline draws, grouped by bucket and folded onto the distinct slugs it
-- reduces to. Touches no disk: this is the SHAPE of the exposure, and classify() below resolves it.
local function collect()
    local buckets = {}

    local function add(bucket, slug, asset)
        if not slug then return end
        local b = buckets[bucket]
        if not b then
            b = { name = bucket, slugs = {}, assets = 0 }
            buckets[bucket] = b
        end
        b.assets = b.assets + 1
        local s = b.slugs[slug]
        if not s then
            s = { slug = slug, uses = 0, examples = {} }
            b.slugs[slug] = s
        end
        s.uses = s.uses + 1
        if #s.examples < 3 then s.examples[#s.examples + 1] = asset end
    end

    -- items/ -- every blueprint, through the composer's own base resolver.
    local items = Registry.load("data/items", "data.items")
    for id, def in pairs(items) do
        add("items", Icon.baseFor(def), id)
    end

    -- chars/ -- every blueprint, through the token composer's own silhouette resolver. Fed the tokenId,
    -- because that is the string the resolver's keyword scan actually reads.
    local chars = Registry.load("data/characters", "data.characters")
    for key, def in pairs(chars) do
        add("chars", Char.slugFor(def, Char.tokenId(key)), key)
    end

    -- traps/ materials/ props/ -- rendered straight from the map by icon-build, one glyph per file, no
    -- composition. `icon = false` means the map deliberately named nothing, so there is no exposure yet.
    if IconMap then
        for assetPath, entry in pairs(IconMap) do
            local bucket = assetPath:match("^([^/]+)/")
            if bucket and DIRECT_BUCKETS[bucket] and type(entry.icon) == "string" then
                add(bucket, entry.icon, assetPath)
            end
        end
    end

    return buckets
end

-- Attach the answering root to each slug, and total the project's DISTINCT exposure. A slug used by two
-- buckets is one piece of art to draw, so it counts once in the totals while each bucket still reports
-- its own view of it.
local function classify(buckets)
    local totals = { art = 0, vendor = 0, missing = 0 }
    local byArtist, outstanding, row = {}, {}, {}

    for _, b in pairs(buckets) do
        b.byRoot = { art = 0, vendor = 0, missing = 0 }
        for slug, s in pairs(b.slugs) do
            local _, root = Source.locate(slug)
            if root ~= "art" and root ~= "vendor" then root = "missing" end
            s.root = root
            b.byRoot[root] = b.byRoot[root] + 1

            if row[slug] then
                -- Same drawing, another bucket: fold the extra uses into the row already listed rather
                -- than double-counting a glyph somebody only has to draw once.
                row[slug].uses = row[slug].uses + s.uses
            else
                row[slug] = { slug = slug, uses = s.uses, examples = s.examples, root = root }
                totals[root] = totals[root] + 1
                if root ~= "art" then
                    outstanding[#outstanding + 1] = row[slug]
                    local artist = slug:match("^([^/]+)/") or "?"
                    byArtist[artist] = (byArtist[artist] or 0) + 1
                end
            end
        end
    end

    table.sort(outstanding, function(a, b)
        if a.uses ~= b.uses then return a.uses > b.uses end
        return a.slug < b.slug
    end)

    -- How many drawings each bucket would still need if the others were already done -- i.e. the slugs
    -- ONLY it uses. This is the number that decides a commission boundary, and it is not the bucket's
    -- own slug count: 464 slugs across the buckets are 410 distinct drawings, so 54 are shared and would
    -- arrive with whichever bucket is drawn first.
    --
    -- It matters most for chars/. Those 191 silhouettes are INTERIM tokens, slated for replacement by
    -- Spine rigs (docs/commission-board-sprites.md) -- so drawing them as flat glyphs is paying for art
    -- the plan already intends to throw away. Knowing how many are chars-only says exactly how much of
    -- the glyph commission that decision removes.
    local owners = {}
    for name, b in pairs(buckets) do
        for slug in pairs(b.slugs) do
            if owners[slug] == nil then
                owners[slug] = name
            elseif owners[slug] ~= name then
                owners[slug] = false -- shared by more than one bucket
            end
        end
    end
    local exclusive, shared = {}, 0
    for slug, owner in pairs(owners) do
        if owner == false then
            if row[slug] and row[slug].root ~= "art" then shared = shared + 1 end
        elseif row[slug] and row[slug].root ~= "art" then
            exclusive[owner] = (exclusive[owner] or 0) + 1
        end
    end

    return totals, byArtist, outstanding, exclusive, shared
end

local function writeFile(rel, text)
    local file, err = io.open(love.filesystem.getSource() .. "/" .. rel, "w")
    if not file then return nil, tostring(err) end
    file:write(text)
    file:close()
    return true
end

-- docs/credits-icons.md, regenerated from what the SHIPPED pipeline draws rather than from what the
-- superseded icon-build stage rendered. Attribution is a licence condition, so this file has to name the
-- artists whose work is actually in the build -- no more, and crucially no fewer.
local function writeCredits(totals, byArtist)
    local artists = {}
    for artist in pairs(byArtist) do artists[#artists + 1] = artist end
    table.sort(artists)

    local out = {}
    local function line(s) out[#out + 1] = s or "" end

    line("# Icon credits")
    line()
    line("GENERATED by `. art-source credits`. Do not hand-edit; re-run instead.")
    line()
    line("This counts the silhouettes the **shipped composers** actually draw, resolved through")
    line("`Icon.baseFor` / `Char.slugFor` -- the same functions the renderer calls. An earlier version of")
    line("this file was generated by `. icon-build`, the sourcing stage the composer superseded, and so")
    line("counted glyphs the build no longer draws. **Do not run `icon-build` to refresh it.**")
    line()
    if totals.vendor == 0 then
        line("**No shipped silhouette comes from game-icons.net.** Every base is drawn art under")
        line("`art/bases/`, so the CC BY 3.0 attribution is retired.")
    else
        line(string.format("This game uses **%d** icons from [game-icons.net](https://game-icons.net),",
            totals.vendor))
        line("licensed under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/).")
        line("**Attribution is a condition of that licence** -- this list must reach players, not just")
        line("the repository. Surface it on the credits screen.")
        line()
        line("> Icons made by " .. table.concat(artists, ", ") .. ".")
        line("> Available on https://game-icons.net")
    end
    line()
    line(string.format("Drawn in-house: **%d** of %d distinct silhouettes.",
        totals.art, totals.art + totals.vendor + totals.missing))
    line()
    line("## Artists")
    line()
    if #artists == 0 then
        line("_None -- no shipped silhouette is third-party._")
    end
    for _, artist in ipairs(artists) do
        line(string.format("- %s -- %d icon(s)", artist, byArtist[artist]))
    end
    if totals.missing > 0 then
        line()
        line(string.format("## Unresolved (%d)", totals.missing))
        line()
        line("Named by a composer but present in neither root -- these draw nothing and are a bug, not a")
        line("commission. Run `. art-source slugs` for the list.")
    end
    line()

    local ok, err = writeFile("docs/credits-icons.md", table.concat(out, "\n"))
    if ok then
        print("  wrote docs/credits-icons.md")
    else
        print("  FAILED to write docs/credits-icons.md: " .. tostring(err))
    end
end

function M.run(args)
    local mode = {}
    for _, a in ipairs(args or {}) do mode[a] = true end

    local buckets = collect()
    local totals, byArtist, outstanding, exclusive, shared = classify(buckets)
    local distinct = totals.art + totals.vendor + totals.missing

    print("")
    print("Shipped silhouettes -- which set answers each slug the composers draw")
    print("")
    print("  bucket        assets   slugs   art/bases   vendor   missing")
    print("  ---------------------------------------------------------------")
    for _, name in ipairs(ORDER) do
        local b = buckets[name]
        if b then
            local n = 0
            for _ in pairs(b.slugs) do n = n + 1 end
            print(string.format("  %-12s %6d  %6d  %10d  %7d  %8d",
                name, b.assets, n, b.byRoot.art, b.byRoot.vendor, b.byRoot.missing))
        end
    end
    print("  ---------------------------------------------------------------")
    print(string.format("  %-12s %6s  %6d  %10d  %7d  %8d",
        "DISTINCT", "-", distinct, totals.art, totals.vendor, totals.missing))
    print("")
    print(string.format("  %d distinct silhouettes still to draw before nothing shipped is game-icons.",
        totals.vendor))
    print("  (a slug shared by two buckets is ONE drawing: counted once here, in both rows above)")

    print("")
    print("  drawings ONLY this bucket needs -- the commission boundary, since a shared slug")
    print("  arrives with whichever bucket is drawn first:")
    for _, name in ipairs(ORDER) do
        if exclusive[name] then
            print(string.format("    %-12s %4d", name, exclusive[name]))
        end
    end
    print(string.format("    %-12s %4d  (needed by two or more)", "shared", shared))

    if next(byArtist) then
        print("")
        print("  still vendored, by game-icons artist:")
        local artists = {}
        for a in pairs(byArtist) do artists[#artists + 1] = a end
        table.sort(artists, function(x, y)
            if byArtist[x] ~= byArtist[y] then return byArtist[x] > byArtist[y] end
            return x < y
        end)
        for _, a in ipairs(artists) do
            print(string.format("    %-18s %4d", a, byArtist[a]))
        end
    end

    if mode.slugs then
        print("")
        print(string.format("  outstanding slugs (%d), most-used first -- drawing the top of this list", #outstanding))
        print("  re-skins the most assets per glyph:")
        print("")
        for _, s in ipairs(outstanding) do
            print(string.format("    %-40s %4d use(s)  %s%s",
                s.slug, s.uses, table.concat(s.examples, ", "),
                s.root == "missing" and "   [MISSING FROM BOTH ROOTS]" or ""))
        end
    end

    if mode.credits then
        print("")
        writeCredits(totals, byArtist)
    end

    -- This verb owns its exit code (main.lua does not stamp one over it), because `ship` is a gate: a
    -- release script has to be able to read a nonzero status, not parse the log for the word FAIL.
    print("")
    if mode.ship then
        if totals.vendor > 0 or totals.missing > 0 then
            print(string.format("SHIP GATE: FAIL -- %d vendored, %d missing.", totals.vendor, totals.missing))
            love.event.quit(1)
            return
        end
        print("SHIP GATE: PASS -- every shipped silhouette is drawn art under art/bases/.")
    else
        print("  (`. art-source slugs` for the list, `credits` to rewrite the credits doc,")
        print("   `ship` to gate a release on it)")
    end
    love.event.quit(0)
end

M.collect = collect
M.classify = classify

return M
