-- Icon renderer: turns tools/icons/map.lua into actual PNGs under assets/.
--
--     & "E:\LOVE\lovec.exe" . icon-build         # render every mapped icon
--     & "E:\LOVE\lovec.exe" . icon-build force   # ... including ones already on disk
--
-- Needs tools/icons/fetch.ps1 (the SVG sources + resvg) and `. icon-map` (the mapping) first.
--
-- For each mapped entry it does three things to the vendored SVG and hands the result to resvg:
--   1. drops the full-canvas background path, so the icon lands on transparency
--   2. rewrites the foreground fill to this asset's colour
--   3. rasterizes at RENDER_SIZE, comfortably above the 64px cell it is drawn into
--
-- Colour is baked in at render time ON PURPOSE: it beats a blanket runtime tint, since each bucket
-- gets its own exact colour at export and costs nothing to change.
--
-- Existing files are skipped unless `force` is passed -- so hand-drawn or purchased art that has
-- replaced a generated icon is never silently overwritten.

local M = {}

local ICON_ROOT = "vendor/game-icons"
local STAGING = "vendor/staging"
local RESVG = "vendor/bin/resvg.exe"
local CREDITS = "docs/credits-icons.md"
-- The player-facing twin of the doc above, read by states/credits.lua. See writeCredits.
local CREDITS_DATA = "data/credits_icons.lua"

-- Rendered edge, in pixels. Items sit in a 64px cell and hazards/traps on a 64px tile; 128 keeps
-- them sharp there and leaves room to raise BOARD_TILE without re-rendering.
local RENDER_SIZE = 128

-- The full-canvas rect every game-icons SVG opens with. Removing it yields a transparent icon.
local BG_PATH = '<path d="M0 0h512v512H0z"/>'

-- Default foreground per bucket. A warm off-white reads as bright fantasy against the dark panels
-- without going stark, and keeps the inventory from looking like a spreadsheet of white glyphs.
local BUCKET_COLOR = {
    items = "#e9e2d0",
    materials = "#e9e2d0",
    traps = "#f0b8a8",
}

local function projectPath(rel)
    return love.filesystem.getSource() .. "/" .. rel
end

-- Hazards used to be special-cased here, tinted per blueprint disposition. They have no art at all
-- any more -- the board draws every zone procedurally through shaders/field.lua -- so there is no
-- hazard bucket for this pipeline to colour. See docs/art-assets.md, "Hazards are not icons".
local function colorFor(bucket)
    return BUCKET_COLOR[bucket] or "#e9e2d0"
end

-- Read the vendored SVG and return it recoloured onto transparency, or nil + why.
local function transform(slug, color)
    local path = ICON_ROOT .. "/" .. slug .. ".svg"
    local svg = love.filesystem.read(path)
    if not svg then return nil, "no such icon: " .. slug end

    local body, removed = svg:gsub(BG_PATH:gsub("%p", "%%%0"), "", 1)
    if removed == 0 then
        -- A handful of icons in the set don't open with the standard rect. Report rather than
        -- silently shipping one with a black square baked behind it.
        return nil, "unexpected SVG layout (no background path): " .. slug
    end

    local filled, n = body:gsub('fill="#fff"', string.format('fill="%s"', color))
    if n == 0 then return nil, "no foreground fill to recolour: " .. slug end

    return filled
end

-- Ensure every directory along `rel` exists inside the project tree.
local function ensureDir(rel)
    local built = nil
    for part in rel:gmatch("[^/]+") do
        built = built and (built .. "/" .. part) or part
        if not love.filesystem.getInfo(built) then
            os.execute(string.format('mkdir "%s" 2>nul', projectPath(built):gsub("/", "\\")))
        end
    end
end

local function writeFile(rel, text)
    local file, err = io.open(projectPath(rel), "w")
    if not file then return nil, tostring(err) end
    file:write(text)
    file:close()
    return true
end

-- Render one staged SVG to PNG via resvg. Returns true, or nil + the failing command.
local function rasterize(svgRel, pngRel)
    local cmd = string.format('"%s" "%s" "%s" --width %d --height %d',
        projectPath(RESVG):gsub("/", "\\"),
        projectPath(svgRel):gsub("/", "\\"),
        projectPath(pngRel):gsub("/", "\\"),
        RENDER_SIZE, RENDER_SIZE)

    -- Wrapped in quotes for cmd.exe, which otherwise eats the first quoted token of the path.
    local ok = os.execute('""' .. cmd:sub(2) .. '"')
    if ok == 0 or ok == true then return true end
    return nil, cmd
end

local function writeCredits(authors, count)
    local names = {}
    for author in pairs(authors) do names[#names + 1] = author end
    table.sort(names)

    local lines = {
        "# Icon credits",
        "",
        "GENERATED by `& \"E:\\LOVE\\lovec.exe\" . icon-build`. Do not hand-edit; re-run instead.",
        "",
        string.format("This game uses %d icons from [game-icons.net](https://game-icons.net),", count),
        "licensed under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/).",
        "**Attribution is a condition of that licence** -- this list must reach players, not just",
        "the repository. Surface it on the credits screen.",
        "",
        "> Icons made by " .. table.concat(names, ", ") .. ".",
        "> Available on https://game-icons.net",
        "",
        "## Artists",
        "",
    }
    for _, author in ipairs(names) do
        lines[#lines + 1] = string.format("- %s — %d icon(s)", author, authors[author])
    end
    lines[#lines + 1] = ""

    writeFile(CREDITS, table.concat(lines, "\n"))

    -- The same pass writes the player-facing twin. The markdown above is for the repository; the CC BY
    -- licence requires the attribution reach PLAYERS, and states/credits.lua reads this. Emitted here
    -- rather than transcribed by hand into the credits screen, because a hand-copied list goes stale
    -- the first time an icon is added -- and stale, for an attribution list, means out of licence.
    local data = {
        "-- GENERATED by `& \"E:\\LOVE\\lovec.exe\" . icon-build`. Do not hand-edit; re-run instead.",
        "--",
        "-- The machine-readable twin of " .. CREDITS .. ". That file is for the repository; this one is",
        "-- for the PLAYER -- states/credits.lua reads it so the game-icons.net attribution reaches the",
        "-- credits screen, which is a condition of the CC BY 3.0 licence and not a courtesy.",
        "return {",
        '    source = "game-icons.net",',
        '    url = "https://game-icons.net",',
        '    licence = "CC BY 3.0",',
        '    licenceUrl = "https://creativecommons.org/licenses/by/3.0/",',
        string.format("    count = %d,", count),
        "    -- Author -> icons used. Sorted by name when written, so the file diffs cleanly.",
        "    authors = {",
    }
    for _, author in ipairs(names) do
        data[#data + 1] = string.format('        { name = %q, count = %d },', author, authors[author])
    end
    data[#data + 1] = "    },"
    data[#data + 1] = "}"
    data[#data + 1] = ""

    writeFile(CREDITS_DATA, table.concat(data, "\n"))
end

function M.run(args)
    local force = false
    for _, a in ipairs(args or {}) do
        if a == "force" then force = true end
    end

    if not love.filesystem.getInfo(RESVG) then
        print("resvg not found at " .. RESVG)
        print("run:  powershell -ExecutionPolicy Bypass -File tools\\icons\\fetch.ps1")
        return
    end

    local ok, map = pcall(function() return require("tools.icons.map") end)
    if not ok or type(map) ~= "table" then
        print("no mapping found -- run:  & \"E:\\LOVE\\lovec.exe\" . icon-map")
        return
    end

    ensureDir(STAGING)

    local keys = {}
    for key in pairs(map) do keys[#keys + 1] = key end
    table.sort(keys)

    local rendered, skipped, unmapped, failures = 0, 0, 0, {}

    for _, key in ipairs(keys) do
        local entry = map[key]
        local outRel = "assets/" .. key

        if not (entry and entry.icon) then
            unmapped = unmapped + 1
        elseif love.filesystem.getInfo(outRel) and not force then
            skipped = skipped + 1
        else
            local bucket = key:match("^([^/]+)/")
            local svg, err = transform(entry.icon, colorFor(bucket))

            if not svg then
                failures[#failures + 1] = key .. " -- " .. err
            else
                local stageRel = STAGING .. "/" .. key:gsub("/", "_"):gsub("%.png$", "") .. ".svg"
                local wrote, werr = writeFile(stageRel, svg)
                if not wrote then
                    failures[#failures + 1] = key .. " -- cannot stage: " .. werr
                else
                    ensureDir(outRel:match("^(.*)/[^/]+$"))
                    local done, cmd = rasterize(stageRel, outRel)
                    if done then
                        rendered = rendered + 1
                    else
                        failures[#failures + 1] = key .. " -- resvg failed: " .. tostring(cmd)
                    end
                end
            end
        end
    end

    print("")
    print(string.format("  %-20s %d", "rendered", rendered))
    print(string.format("  %-20s %d", "already present", skipped))
    print(string.format("  %-20s %d", "no icon mapped", unmapped))
    print(string.format("  %-20s %d", "failed", #failures))
    print("")

    for _, f in ipairs(failures) do print("  fail: " .. f) end

    -- Attribution is derived from the MAP and what is on disk, never from what this run happened to
    -- render. A second run renders nothing and must still credit every artist whose icon ships --
    -- getting this wrong would under-credit them and break the CC BY 3.0 terms.
    local authors, shipped = {}, 0
    for _, key in ipairs(keys) do
        local entry = map[key]
        if entry and entry.icon and love.filesystem.getInfo("assets/" .. key) then
            local author = entry.icon:match("^([^/]+)/")
            authors[author] = (authors[author] or 0) + 1
            shipped = shipped + 1
        end
    end

    if shipped > 0 then
        writeCredits(authors, shipped)
        print(string.format("wrote %s -- %d icons, %s. This must reach the credits screen (CC BY 3.0)",
            CREDITS, shipped, "attribution required"))
    end
end

return M
